server:
  port: 801
spring:
  application:
    name: cloud-consumer-order-service
eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己
    fetch-registry: true #是否从eurekaServer抓取已有的server信息，默认为true，单节点无所谓，集群必须设置为true
    service-url:
      #defaultZone: http://localhost:7001/eureka/ #单机
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群